#!/bin/sh
#
# Shell script to test the Debian Docker image.
#
# Copyright 2016-2020, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

# Variables
DEBCONF_NONINTERACTIVE_SEEN="true"
DEBIAN_FRONTEND="noninteractive"


echo "=== Docker Build Test ==="

printf '[TEST] Check if apt command is installed... '
if dpkg -s apt > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 1
fi

printf '[TEST] Check package installation with apt... '
if (apt-get -qq update && apt-get -y -qq install less > /dev/null 2>&1 && less --version > /dev/null 2>&1); then
  echo 'OK'
else
  echo 'Failed'
  exit 2
fi

printf '[TEST] Check if debootstrap dir was removed... '
if [ ! -e /debootstrap ]; then
  echo 'OK'
else
  echo 'Failed'
  exit 3
fi

printf '[TEST] Check if packages are correctly installed... '
if [ $(apt-get -qq -s install $(dpkg-query -W -f "\${Package} ") | wc -l) -eq "0" ]; then
  echo 'OK'
else
  echo 'Failed'
  exit 4
fi

exit 0
